# Generated by Django 5.2.17 on 2026-08-19 01:42

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
            ],
            options={
                'verbose_name': 'исполнитель',
                'verbose_name_plural': 'исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлена')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('release_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1860), catalog.models.validate_release_year], verbose_name='год выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist', verbose_name='исполнитель')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'ordering': ['artist__name', 'release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядковый номер')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.album', verbose_name='альбом')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_entries', to='catalog.song', verbose_name='песня')),
            ],
            options={
                'verbose_name': 'трек',
                'verbose_name_plural': 'треки',
                'ordering': ['album', 'track_number'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['release_year'], name='catalog_alb_release_8e6732_idx'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('artist', 'title'), name='unique_album_per_artist', violation_error_message='У этого исполнителя уже есть альбом с таким названием.'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.CheckConstraint(condition=models.Q(('release_year__gte', 1860), ('release_year__lte', 2100)), name='album_release_year_range', violation_error_message='Год выпуска вне допустимого диапазона.'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='unique_track_number_per_album', violation_error_message='Этот номер уже занят в альбоме.'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='unique_song_per_album', violation_error_message='Эта песня уже есть в альбоме.'),
        ),
    ]
